apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-prod.yaml
    path: tree/main/helm
    repoURL: https://github.com/gmj06/SUSE_CloudNativeApplication_TechTrends_Project/
    targetRevision: HEAD
