## provide the name of the namespace
namespace:
  name: staging

## provide the name of the application

## define the image to execute with the Deployment
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

## set the number of replicas for an application
replicaCount: 3

## set the service information
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

## set CPU and memory  resources
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

## set the container Port
containerPort: 3111

## set the livenessProbe and readinessProbe path
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
